title: yunjian's world
subtitle: hello world
description: ''
keywords: blog
author: yunjianshijie
language: zh-CN
timezone: Asia/Shanghai
url: http://example.com
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
banner_img: https://i0.hdslb.com/bfs/article/95f73d9fa17b3ca67c1c81b3ce6479c5f15474e8.jpg@1256w_540h_!web-article-pic.avif  # 全局大图

filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: '' 
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: fluid # nexmoe
force_https: true
deploy:
  type: ''




## 关于
about:
  avatar: /img/elysia1.jpg  #   avatar.png
  name: "云间世界"
  intro: "顺着风的方向" 
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/yunjianshijie', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

## 导航菜单
navbar:
  blog_title: 云间的小小世界
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }
    - { key: 'archives', link: '/archives/', icon: 'iconfont icon-archives-fill', name: '归档' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    



## 展示 PV 与 UV 统计
footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"


index:
  slogan: ## 开头打字机
    enable: true
    text: 顺着风的方向
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  auto_excerpt: ##文章摘要 
    enable: false
  post_meta: ## 文章信息
    date: true
    category: true
    tag: true

## 打印机设置
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
## 代码块
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true
## 脚注
post:
  footnote:
    enable: true
    header: ''

## 友联
links:
  items:
    - {
      title: 'Fluid Docs', 
      intro: 'yyyy', ##简介
      link: 'https://blog.phom.space/',
      avatar: '/img/favicon.png' ##头像
    }
  default_avatar: /img/avatar.png




