title: 云间的小小世界
subtitle: hello world
description: ''
keywords: blog
author: yunjianshijie
language: zh-CN
timezone: Asia/Shanghai
url: http://example.com
#permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink.html  ## 此处可以自己设置
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: falseT
external_link:
  enable: true
  field: site
  exclude: ''


filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: '' 
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: fluid # nexmoe
force_https: true
deploy:
  type: ''




## 关于
about:
  banner_img: /img/yuye1.png
  avatar: https://q.qlogo.cn/headimg_dl?dst_uin=2098600899&spec=640&img_type=jpg #   avatar.png
  name: "云间世界"
  intro: "顺着风的方向" 
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/yunjianshijie', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

## 导航菜单
navbar:
  blog_title: 云间的小小世界
  # menu:
  #   - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
  #   - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
  #   - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }
  #   - { key: 'archives', link: '/archives/', icon: 'iconfont icon-archives-fill', name: '归档' }
  #   - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }



## 展示 PV 与 UV 统计
footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"


index:
  banner_img:  /img/yuye1.png # https://sm.ms/image/9iWy27mcvhU4qXP # 全局大图
  slogan: ## 开头打字机
    enable: true
    text: 顺着风的方向
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  auto_excerpt: ##文章摘要 
    enable: false
  post_meta: ## 文章信息
    date: true
    category: true
    tag: true

## 打印机设置
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
## 代码块
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true
## 脚注
post:
  footnote:
    enable: true
    header: ''

## 友联
links:
  banner_img: /img/yuye1.png
  items:
    - {
      title: 'Ph0m', 
      intro: '贵在坚持', ##简介
      link: 'https://blog.phom.space/',
      avatar: https://files.superbed.cn/store/images/dd/6a/65e1df0c9f345e8d03bcdd6a.png ##头像
    }
    - {
      title: 'future', 
      intro: 'Hang on to your dreams ! ', ##简介
      link: 'https://future.thisis.host/',
      avatar: https://q1.qlogo.cn/g?b=qq&nk=1305969480&s=3 ##头像
    }
    - {
      title: 'tiny-sky', 
      intro: '​人生苦短，及时行乐.', ##简介
      link: 'https://tiny-sky.github.io/',
      avatar: https://tiny-sky.github.io/img/tiny-sky.png
    }
    - {
      title: 'g0ubu1i', 
      intro: '君子不器。', ##简介
      link: 'https://blog.goubuli.online/',
      avatar: https://q.qlogo.cn/headimg_dl?dst_uin=1738327323&spec=640&img_type=jpg
    }
  default_avatar: /img/avatar.png



# ## abbrlink config
# abbrlink:
#   alg: crc32      #support crc16(default) and crc32 进制
#   rep: hex        #support dec(default) and hex  算法
#   drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
#   ## Generate categories from directory-tree
#   ## depth: the max_depth of directory-tree you want to generate, should > 0
#   auto_category:
#      enable: true  #true(default)
#      depth:        #3(default)
#      over_write: false 
#   auto_title: false #enable auto title, it can auto fill the title by path
#   auto_date: false #enable auto date, it can auto fill the date by time today
#   force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.